# Generated by Django 5.0 on 2023-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_user_id_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
