# Generated by Django 5.0 on 2023-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_auth', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
