# Generated by Django 5.0 on 2023-12-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_auth', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
